Adx 477 access request email org admins
fjelltopp/ckanext-restricted pull request #30
Opened 2020-11-25 16:19 UTC by Manoj-nathwani

# Problem
- Sometimes a dataset does not have a maintainer set, so emails to request access to it kinda go nowhere. Only our internal unattended fjelltopp email is sent an email informing us

# Solution
- Email all org admins which the dataset belongs to notifying them

2020-11-25 16:52 UTC, tomeksabala requested changes
A few small changes.

I also think it'd be great to add a few more tests for this:
`test_both_org_admin_and_maintainer_are_emailed_on_request_access` - single admin in org and maintainer provided
`test_org_admin_is_emailed_if_no_maintaner_on_request_access` - a single admin and no maintainer info provided
`test_only_org_admins_are_emailed_on_request_access` - an admin, editor, and member in the owner org and only the admin is e-mailed.

2020-11-25 16:52 UTC, tomeksabala commented on ckanext/restricted/controller.py
> +                .all()
Usually we use line breaks without \
sth like:
```
model.Session.query(model.User).filter(
                    model.User.id.in_(dataset_org_admins),
                    model.User.email.isnot(None)
).all()
```

2020-11-25 16:52 UTC, tomeksabala commented on ckanext/restricted/controller.py
> +            dataset_org_admins = [
please change the var name to `dataset_org_admin_ids`.
It's generally a bad practice to mutate variables if you don't have to (this var is reassigned a new value in :105)

2020-11-25 16:52 UTC, tomeksabala commented on ckanext/restricted/tests/test_plugin.py
> +        assert user_3['email'] not in email_recipients, \
why a line break here? We have set a line length to 127

2020-11-25 16:52 UTC, tomeksabala commented on ckanext/restricted/tests/test_plugin.py
> +        user_3 = factories.User(email='user_3@example.com')
if you name the variables differently the comment "# create two admins and one regular member of an org" won't be needed
```
admin1 = factories
admin2 = factories
member = factories
```

2020-11-26 12:11 UTC, Manoj-nathwani commented
I've amended the tests, there's no need to create more as it would mean we'd duplicate a lot of code.

I'm testing:
- dataset maintainer is emailed
- dataset org admins get emails
- dataset org editors & members do not

2020-11-27 08:03 UTC, tomeksabala requested changes
Great, the code looks good now. About the tests however: I'd suggest going with my initial suggestion and creating 4 separate test methods. Don't worry about duplication (if you see any, just extract common logic into a function. This can be done for test setup (given), action (when) and even assert (then)). Having those 4 separate test cases is going to do better job at testing the feature which a single "do it all" test does not. Also it improves the readability a lot in case of a failing test report.
I'm happy to explain it more in a call if it's not clear.

2020-12-01 14:48 UTC, Manoj-nathwani commented
@tomeksabala apologies for the delay - this is now ready to be merged in 🚀

2020-12-01 15:09 UTC, tomeksabala approved these changes
"This is the way", LGTM :+1:

2020-12-01 15:13 UTC, merged