ADX-549 Fix for unicode organization names and usernames in restricte…
fjelltopp/ckanext-restricted pull request #35
Opened 2020-12-09 15:08 UTC by tomeksabala

…d_string.html

2020-12-09 17:03 UTC, Manoj-nathwani requested changes

2020-12-09 17:03 UTC, Manoj-nathwani commented on ckanext/restricted/templates/restricted/restricted_string.html
> +        {% trans users=users_popup|safe %}
This is cool! I wasn't aware you could do this. I guess this is a specific feature of `{% trans }` to allow you to define variables when initialising it

2020-12-10 06:43 UTC, tomeksabala commented on ckanext/restricted/templates/restricted/restricted_string.html
> +    Access restricted to members of {{ organization }}.
No it's not. Earlier:
```
{% set organization_link = h.link_to(pkg.organization.title, h.url_for("organization.read", id=pkg.organization.name)) %}
```
So `organization_link` is a html. We put `{{ organization }}` in the trans string for ease of translator. With:
```
{% trans organization=organization_link|safe %}
```
you can see that it's actually non-escaped html link with format `<a href="url">organization_name</a>`.

2020-12-10 10:10 UTC, Manoj-nathwani approved these changes
Looks like I wasn't aware how `{% trans %}` worked, so this is all good 👍

2020-12-10 10:10 UTC, merged